<?php

declare(strict_types=1);

namespace App\Tests\Architecture\PhpatRules;

use PHPat\Selector\Selector;
use PHPat\Test\Builder\Rule;
use PHPat\Test\PHPat;

/**
 * Naming and shape of the Application layer.
 *
 * The naming rule is not cosmetic. `docs/SERVICES.md` is generated by scanning every
 * `Application/Service` directory for classes whose name ends in `Service`, and a class
 * that does not follow the convention is
 * simply absent from the inventory — which means the next contributor does not know it
 * exists and writes a second one.
 */
final class ApplicationShapeRules
{
    public function test_application_services_are_named_service(): Rule
    {
        return PHPat::rule()
            ->classes(Selector::inNamespace('/^App\\\\[A-Za-z]+\\\\Application\\\\Service/', true))
            ->excluding(Selector::isInterface(), Selector::isAbstract(), Selector::isEnum())
            ->shouldBeNamed('/Service$/', true)
            ->because('docs/SERVICES.md is generated from the *Service naming convention; an off-convention class is invisible to it (INV-10)');
    }

    public function test_facades_are_named_facade(): Rule
    {
        return PHPat::rule()
            ->classes(Selector::classname('/^App\\\\[A-Za-z]+\\\\Application\\\\[A-Za-z]+Facade$/', true))
            ->shouldBeFinal()
            ->because('a facade is a context\'s single front door and must not be extended (ADR-0006)');
    }
}
