<?php

declare(strict_types=1);

/*
 * Formatting is settled here so it is never discussed in review. `make fix` applies it;
 * `make lint` and the pre-commit hook check it.
 *
 * Risky rules ARE enabled. They change behaviour, which is the point: `declare_strict_types`
 * and `strict_comparison` are exactly the guarantees this codebase relies on, and leaving
 * them optional would mean some files have them and some do not.
 */

$finder = (new PhpCsFixer\Finder())
    ->in([__DIR__.'/src', __DIR__.'/tests', __DIR__.'/fixtures', __DIR__.'/config', __DIR__.'/public'])
    ->notPath('reference.php')      // auto-generated by flex; says so in its own header
    ->exclude('Maker/skeleton')     // templates, not programs
    ->append([__FILE__, __DIR__.'/rector.php']);

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setParallelConfig(PhpCsFixer\Runner\Parallel\ParallelConfigFactory::detect())
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        '@PHP85Migration' => true,
        '@PHPUnit11x0Migration:risky' => true,

        // Non-negotiables for this codebase.
        'declare_strict_types' => true,
        'strict_comparison' => true,
        'strict_param' => true,
        'native_function_invocation' => ['include' => ['@compiler_optimized'], 'scope' => 'namespaced'],

        // Readability of the parts people actually read.
        'ordered_imports' => ['sort_algorithm' => 'alpha', 'imports_order' => ['class', 'function', 'const']],
        'ordered_class_elements' => ['order' => [
            'use_trait', 'case', 'constant_public', 'constant_protected', 'constant_private',
            'property_public', 'property_protected', 'property_private',
            'construct', 'destruct', 'magic', 'phpunit',
            'method_public', 'method_protected', 'method_private',
        ]],
        'global_namespace_import' => ['import_classes' => true, 'import_functions' => false, 'import_constants' => false],
        'no_superfluous_phpdoc_tags' => ['allow_mixed' => true, 'remove_inheritdoc' => true],
        'phpdoc_to_comment' => false,   // @responsibility lives in a docblock and must stay one

        // PHP 8.4+ allows `new Foo()->bar()`, and @PHP85Migration strips the parentheses by
        // default. pdepend — which PHPMD is built on, and whose newest stable release predates
        // 8.4 — cannot parse that form: PHPMD reports a parse error and SILENTLY SKIPS the
        // file, dropping size and complexity enforcement on it while still reporting success.
        // Rector's NewMethodCallWithoutParenthesesRector is skipped for the same reason.
        // Revisit when PHPMD 3 ships.
        'new_expression_parentheses' => ['use_parentheses' => true],

        // Keep diffs small and reviews about behaviour.
        'concat_space' => ['spacing' => 'none'],
        'trailing_comma_in_multiline' => ['elements' => ['arrays', 'arguments', 'parameters', 'match']],
        'yoda_style' => true,
    ])
    ->setFinder($finder);
