<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;

/*
 * Rector runs in --dry-run mode in CI: it reports what it would change and fails the build
 * if anything is outstanding. `make fix` applies it.
 *
 * Kept deliberately narrow. Rector is very good at mechanical modernisation and very bad at
 * knowing which abstraction you meant, so the sets here are the ones whose output is always
 * reviewable line by line.
 */
return RectorConfig::configure()
    ->withPaths([
        __DIR__.'/src',
        __DIR__.'/tests',
        __DIR__.'/fixtures',
    ])
    ->withSkip([
        // Auto-generated by flex.
        __DIR__.'/config/reference.php',
        // Maker skeletons are templates rendered with variables that do not exist here.
        __DIR__.'/src/Maker/skeleton',
        // Migrations are a historical record. Rewriting an applied migration changes what
        // the schema did on a database that has already run it.
        __DIR__.'/migrations',
    ])
    ->withPhpSets()
    ->withPreparedSets(
        deadCode: true,
        codeQuality: true,
        typeDeclarations: true,
        earlyReturn: true,
        privatization: true,
    )
    ->withImportNames(importShortClasses: false, removeUnusedImports: true);
