<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Field-level entity history (ADR-0017).
 *
 * These tables are derived from the audited-entity list in AuditorFactory, not from Doctrine
 * mappings, so  cannot see them. The statements were produced by
 *  and pasted here ON PURPOSE: a schema change
 * that happens outside the migration history is how two environments end up different in ways
 * nobody can reconstruct.
 *
 * After changing AuditorFactory::AUDITED_ENTITIES, re-run that command and add a new
 * migration with whatever it emits.
 */
final class Version20260822194701 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Entity-history tables for the auditor core library (ADR-0017)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE "user_audit" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX type_300bf7626cdb4235843c548a907a53a5_idx ON "user_audit" (type)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX object_id_300bf7626cdb4235843c548a907a53a5_idx ON "user_audit" (object_id)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX discriminator_300bf7626cdb4235843c548a907a53a5_idx ON "user_audit" (discriminator)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX transaction_hash_300bf7626cdb4235843c548a907a53a5_idx ON "user_audit" (transaction_hash)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX blame_id_300bf7626cdb4235843c548a907a53a5_idx ON "user_audit" (blame_id)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX created_at_300bf7626cdb4235843c548a907a53a5_idx ON "user_audit" (created_at)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE acl_entry_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX type_5d5676630c58f68ecdcf7766a3188240_idx ON acl_entry_audit (type)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX object_id_5d5676630c58f68ecdcf7766a3188240_idx ON acl_entry_audit (object_id)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX discriminator_5d5676630c58f68ecdcf7766a3188240_idx ON acl_entry_audit (discriminator)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX transaction_hash_5d5676630c58f68ecdcf7766a3188240_idx ON acl_entry_audit (transaction_hash)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX blame_id_5d5676630c58f68ecdcf7766a3188240_idx ON acl_entry_audit (blame_id)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX created_at_5d5676630c58f68ecdcf7766a3188240_idx ON acl_entry_audit (created_at)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE group_membership_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX type_0b0536c43e6c5fc327ae2f2caf29ee55_idx ON group_membership_audit (type)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX object_id_0b0536c43e6c5fc327ae2f2caf29ee55_idx ON group_membership_audit (object_id)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX discriminator_0b0536c43e6c5fc327ae2f2caf29ee55_idx ON group_membership_audit (discriminator)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX transaction_hash_0b0536c43e6c5fc327ae2f2caf29ee55_idx ON group_membership_audit (transaction_hash)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX blame_id_0b0536c43e6c5fc327ae2f2caf29ee55_idx ON group_membership_audit (blame_id)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX created_at_0b0536c43e6c5fc327ae2f2caf29ee55_idx ON group_membership_audit (created_at)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE role_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX type_92317bf7adb4788531df0b1cb910b5fc_idx ON role_audit (type)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX object_id_92317bf7adb4788531df0b1cb910b5fc_idx ON role_audit (object_id)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX discriminator_92317bf7adb4788531df0b1cb910b5fc_idx ON role_audit (discriminator)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX transaction_hash_92317bf7adb4788531df0b1cb910b5fc_idx ON role_audit (transaction_hash)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX blame_id_92317bf7adb4788531df0b1cb910b5fc_idx ON role_audit (blame_id)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX created_at_92317bf7adb4788531df0b1cb910b5fc_idx ON role_audit (created_at)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE user_group_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX type_a4bc8ab25a6837c0f34558522af8b8c8_idx ON user_group_audit (type)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX object_id_a4bc8ab25a6837c0f34558522af8b8c8_idx ON user_group_audit (object_id)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX discriminator_a4bc8ab25a6837c0f34558522af8b8c8_idx ON user_group_audit (discriminator)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX transaction_hash_a4bc8ab25a6837c0f34558522af8b8c8_idx ON user_group_audit (transaction_hash)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX blame_id_a4bc8ab25a6837c0f34558522af8b8c8_idx ON user_group_audit (blame_id)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX created_at_a4bc8ab25a6837c0f34558522af8b8c8_idx ON user_group_audit (created_at)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE user_role_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX type_f0a783b709873903595ba091602ac41f_idx ON user_role_audit (type)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX object_id_f0a783b709873903595ba091602ac41f_idx ON user_role_audit (object_id)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX discriminator_f0a783b709873903595ba091602ac41f_idx ON user_role_audit (discriminator)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX transaction_hash_f0a783b709873903595ba091602ac41f_idx ON user_role_audit (transaction_hash)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX blame_id_f0a783b709873903595ba091602ac41f_idx ON user_role_audit (blame_id)
            SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX created_at_f0a783b709873903595ba091602ac41f_idx ON user_role_audit (created_at)
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS "user_audit"');
        $this->addSql('DROP TABLE IF EXISTS acl_entry_audit');
        $this->addSql('DROP TABLE IF EXISTS group_membership_audit');
        $this->addSql('DROP TABLE IF EXISTS role_audit');
        $this->addSql('DROP TABLE IF EXISTS user_group_audit');
        $this->addSql('DROP TABLE IF EXISTS user_role_audit');
    }
}
